"""HTTP-level tests for the "attachments table not migrated yet" failure
mode (REQ-CAL-REV-ATTACH-001, 2026-09-23 follow-up).

Root cause this file locks in a regression test for: before this fix, any
route touching StaffReviewSummaryAttachment against a database missing
database/migrations/2026-09-23-create-staff-review-summary-attachments.sql
raised an UNHANDLED psycopg.errors.UndefinedTable, which propagated past
Starlette's CORSMiddleware (whose response-header injection only applies
to responses that flow back out through its own wrapped `send` — an
unhandled exception's fallback 500, generated by the outer
ServerErrorMiddleware, never does). The browser therefore saw a response
with no Access-Control-Allow-Origin header and reported a bare network
failure ("Failed to fetch" / "We couldn't connect") instead of the real,
fixable reason.

This file never uses a real Postgres connection — it runs entirely against
the same isolated in-memory SQLite database every other test in this repo
uses (backend/tests/calendar_auth_test_support.py), and SURGICALLY
SIMULATES the exact real-world psycopg.errors.UndefinedTable /
sqlalchemy.exc.ProgrammingError shape by monkeypatching Session.execute to
raise it only for statements that reference
staff_review_summary_attachments — every other query (staff lookups,
StaffReviewSummary itself, ...) still runs for real against the SQLite
database underneath. This is the practical, disposable-database-equivalent
way to test a real-database-only failure mode without ever opening a real
Postgres connection (see the conversation record for why a real
transaction-wrapped dry run against the actual local Postgres was used
separately, once, outside of any committed test, to confirm the DDL itself
and discover the REFERENCES-privilege gap — that dry run is not repeated
here).

Run with:
    python -m unittest backend.tests.test_review_summary_attachments_missing_table
"""

import unittest
import zlib
from contextlib import contextmanager
from datetime import datetime, timezone
from unittest import mock

from fastapi.testclient import TestClient
from psycopg.errors import UndefinedTable
from sqlalchemy.exc import ProgrammingError
from sqlalchemy.orm import Session

from backend.attachment_storage import FakeAttachmentStorage, get_attachment_storage
from backend.database import get_db
from backend.main import app
from backend.models import StaffDashboardRecord
from backend.routers.staff_review_summaries import (
    _ATTACHMENT_STORAGE_NOT_READY_MESSAGE,
    _is_missing_attachment_table_error,
)
from backend.tests.calendar_auth_test_support import (
    assert_isolated_sqlite_override,
    bearer_header,
    forbid_real_database_engine,
    make_sqlite_engine_and_session_factory,
    patched_calendar_auth_env,
)


def _fake_undefined_table_error() -> ProgrammingError:
    orig = UndefinedTable(
        'relation "management_aios.staff_review_summary_attachments" does not exist'
    )
    return ProgrammingError("SELECT ...", {}, orig)


class MissingTableHelperUnitTests(unittest.TestCase):
    """Pure unit tests — no DB, no HTTP — for the classifier itself."""

    def test_recognizes_a_real_undefined_table_error(self):
        self.assertTrue(_is_missing_attachment_table_error(_fake_undefined_table_error()))

    def test_does_not_misclassify_an_unrelated_programming_error(self):
        other = ProgrammingError("SELECT ...", {}, RuntimeError("some other DB error"))
        self.assertFalse(_is_missing_attachment_table_error(other))

    def test_does_not_misclassify_a_non_programming_error(self):
        self.assertFalse(_is_missing_attachment_table_error(ValueError("not a DB error at all")))


@contextmanager
def simulate_missing_attachment_table():
    """Monkeypatches Session.execute so that any statement mentioning
    staff_review_summary_attachments raises the exact
    sqlalchemy.exc.ProgrammingError(psycopg.errors.UndefinedTable) shape a
    real un-migrated Postgres database produces — every other statement
    (staff lookups, the summary row itself, ...) still executes for real
    against the test's own isolated SQLite database underneath."""
    original_execute = Session.execute

    def patched_execute(self, statement, *args, **kwargs):
        if "staff_review_summary_attachments" in str(statement):
            raise _fake_undefined_table_error()
        return original_execute(self, statement, *args, **kwargs)

    with mock.patch.object(Session, "execute", patched_execute):
        yield


class MissingAttachmentTableTestCase(unittest.TestCase):
    """Same isolated-SQLite + FakeAttachmentStorage setup as
    test_review_summary_attachments.py — see that file's own setUp for the
    full rationale of each safety guard."""

    def setUp(self):
        self.engine, self.SessionLocal = make_sqlite_engine_and_session_factory()

        def override_get_db():
            db = self.SessionLocal()
            try:
                yield db
            finally:
                db.close()

        app.dependency_overrides[get_db] = override_get_db
        assert_isolated_sqlite_override(app, self.engine, get_db_dependency=get_db)
        self.forbid_real_db_ctx = forbid_real_database_engine()
        self.forbid_real_db_ctx.__enter__()

        self.storage = FakeAttachmentStorage()
        app.dependency_overrides[get_attachment_storage] = lambda: self.storage

        self.env_ctx = patched_calendar_auth_env()
        self.env_ctx.__enter__()
        self.client_ctx = TestClient(app)
        self.client = self.client_ctx.__enter__()

    def tearDown(self):
        self.client_ctx.__exit__(None, None, None)
        self.env_ctx.__exit__(None, None, None)
        self.forbid_real_db_ctx.__exit__(None, None, None)
        app.dependency_overrides.clear()
        self.engine.dispose()

    def seed_staff(self, source_record_key="staff-missing-table", full_name="Missing Table Staff"):
        session = self.SessionLocal()
        now = datetime.now(timezone.utc)
        staff = StaffDashboardRecord(
            id=zlib.crc32(source_record_key.encode("utf-8")),
            staff_code="DWL-" + source_record_key,
            name=full_name,
            synced_at=now, created_at=now, updated_at=now,
        )
        session.add(staff)
        session.commit()
        session.refresh(staff)
        staff_id = staff.id
        session.close()
        return staff_id

    # ── LIST (review history) — the reported "We couldn't connect" case ──

    def test_list_returns_controlled_503_with_cors_header_not_a_bare_500(self):
        # A record must actually exist — an empty result set never calls
        # _to_out (and therefore never touches the attachments table) at
        # all, so this test would trivially pass for the wrong reason
        # without one.
        staff_id = self.seed_staff()
        from backend.models import StaffReviewSummary
        session = self.SessionLocal()
        now = datetime.now(timezone.utc)
        session.add(StaffReviewSummary(
            reviewer_member_key="mayurika", reviewed_staff_id=staff_id,
            meeting_date=now.date(), summary_text="Pre-existing summary.",
            created_at=now, updated_at=now,
        ))
        session.commit()
        session.close()

        with simulate_missing_attachment_table():
            resp = self.client.get(
                "/api/staff-review-summaries",
                params={"reviewed_staff_id": staff_id, "reviewer_member_key": "mayurika"},
                headers=dict(bearer_header("mayurika"), Origin="http://127.0.0.1:8080"),
            )
        self.assertEqual(resp.status_code, 503)
        self.assertEqual(
            resp.headers.get("access-control-allow-origin"), "http://127.0.0.1:8080"
        )
        body = resp.json()
        self.assertEqual(body["detail"]["error"], "attachment_storage_not_ready")
        self.assertEqual(body["detail"]["message"], _ATTACHMENT_STORAGE_NOT_READY_MESSAGE)

    def test_detail_route_also_returns_controlled_503(self):
        # A record must exist for _get_active_summary_or_404 to succeed
        # before the (simulated-failing) attachment lookup ever runs —
        # seed it with the real StaffReviewSummary table (unaffected by
        # the simulation, which only targets the attachments table).
        staff_id = self.seed_staff(source_record_key="staff-detail-missing")
        from backend.models import StaffReviewSummary
        session = self.SessionLocal()
        now = datetime.now(timezone.utc)
        record = StaffReviewSummary(
            reviewer_member_key="mayurika", reviewed_staff_id=staff_id,
            meeting_date=now.date(), summary_text="Pre-existing summary.",
            created_at=now, updated_at=now,
        )
        session.add(record)
        session.commit()
        session.refresh(record)
        summary_id = record.id
        session.close()

        with simulate_missing_attachment_table():
            resp = self.client.get(
                "/api/staff-review-summaries/" + str(summary_id),
                headers=dict(bearer_header("mayurika"), Origin="http://127.0.0.1:8080"),
            )
        self.assertEqual(resp.status_code, 503)
        self.assertEqual(resp.json()["detail"]["error"], "attachment_storage_not_ready")

    # ── Upload — the reported "Failed to fetch" case ────────────────────

    def test_upload_returns_controlled_503_and_never_calls_storage(self):
        with simulate_missing_attachment_table():
            resp = self.client.post(
                "/api/staff-review-summaries/attachments",
                files={"file": ("clip.mp3", b"fake-mp3-bytes", "audio/mpeg")},
                headers=dict(bearer_header("mayurika"), Origin="http://127.0.0.1:8080"),
            )
        self.assertEqual(resp.status_code, 503)
        self.assertEqual(
            resp.headers.get("access-control-allow-origin"), "http://127.0.0.1:8080"
        )
        self.assertEqual(resp.json()["detail"]["error"], "attachment_storage_not_ready")
        # The pre-flight check runs BEFORE storage.upload() — a real file
        # must never be uploaded to Cloudinary when it can never be
        # tracked (no row can be written for it).
        self.assertEqual(self.storage.uploaded_public_ids, [])

    # ── Create/update degrade gracefully — never a false failure for an
    #    already-committed write ──────────────────────────────────────────

    def test_text_only_create_still_succeeds_with_empty_attachments(self):
        staff_id = self.seed_staff(source_record_key="staff-create-missing")
        with simulate_missing_attachment_table():
            resp = self.client.post(
                "/api/staff-review-summaries",
                json={
                    "reviewed_staff_id": staff_id,
                    "meeting_date": "2026-09-20",
                    "summary_text": "Created despite the missing attachments table.",
                    "attachment_ids": [],
                },
                headers=bearer_header("mayurika"),
            )
        self.assertEqual(resp.status_code, 201)
        self.assertEqual(resp.json()["attachments"], [])
        self.assertEqual(
            resp.json()["summary_text"], "Created despite the missing attachments table."
        )

    def test_create_with_nonempty_attachment_ids_fails_cleanly_before_any_write(self):
        """Unlike the text-only case, a create that actually references
        attachment_ids cannot silently succeed — _claim_pending_attachments
        runs BEFORE the summary insert, so this is a clean 503 with
        nothing written, not a false success."""
        staff_id = self.seed_staff(source_record_key="staff-create-with-ids")
        fake_attachment_id = "00000000-0000-0000-0000-000000000000"
        with simulate_missing_attachment_table():
            resp = self.client.post(
                "/api/staff-review-summaries",
                json={
                    "reviewed_staff_id": staff_id,
                    "meeting_date": "2026-09-20",
                    "summary_text": "Should not be created.",
                    "attachment_ids": [fake_attachment_id],
                },
                headers=bearer_header("mayurika"),
            )
        self.assertEqual(resp.status_code, 503)
        self.assertEqual(resp.json()["detail"]["error"], "attachment_storage_not_ready")

    # ── PDF/ZIP export must keep working exactly as it did before this
    #    feature existed (pre-existing, text-only behavior) ──────────────

    def test_pdf_export_still_succeeds_treating_attachments_as_empty(self):
        staff_id = self.seed_staff(source_record_key="staff-pdf-missing")
        from backend.models import StaffReviewSummary
        session = self.SessionLocal()
        now = datetime.now(timezone.utc)
        session.add(StaffReviewSummary(
            reviewer_member_key="mayurika", reviewed_staff_id=staff_id,
            meeting_date=now.date(), summary_text="Pre-existing text-only summary.",
            created_at=now, updated_at=now,
        ))
        session.commit()
        session.close()

        with simulate_missing_attachment_table():
            resp = self.client.get(
                "/api/staff-review-summaries/export/pdf",
                params={"reviewed_staff_id": staff_id, "reviewer_member_key": "mayurika"},
                headers=bearer_header("mayurika"),
            )
        self.assertEqual(resp.status_code, 200)
        self.assertEqual(resp.headers.get("content-type"), "application/pdf")


if __name__ == "__main__":
    unittest.main()
