"""Unit tests for backend/review_summary_pdf_export.py (REQ-CAL-REV-PDF-003
Gate B).

Exercises the pure PDF-generation module directly (no HTTP, no database) —
HTTP-level export-route tests live in
backend/tests/test_staff_review_summaries.py, matching the existing
convention where xlsx_export.py's own row/format logic and
member_schedules.py's route are tested separately.

Uses pypdf (test-only — see backend/requirements.txt's own comment; never
imported by any production code path) to parse generated bytes and extract
text for content assertions. Every record in every test here is fabricated,
invented test data — never a value read from a real staff/review record.

Run with: python -m unittest backend.tests.test_review_summary_pdf_export
"""

import builtins
import inspect
import unittest
from datetime import date, datetime, timezone
from io import BytesIO
from pathlib import Path

from pypdf import PdfReader

from backend.config import MEMBER_DIRECTORY, MEMBER_LABELS
from backend.review_summary_pdf_export import (
    build_content_disposition_header,
    build_review_summary_pdf,
    build_review_summary_pdf_filename,
    resolve_reviewer,
    reviewer_scope_label_for,
)


def _fabricated_record(
    reviewer_member_key="mayurika",
    meeting_date=None,
    summary_text="Fabricated summary text.",
    created_at=None,
    updated_at=None,
):
    now = datetime(2026, 1, 15, 9, 30, tzinfo=timezone.utc)
    return {
        "reviewer_member_key": reviewer_member_key,
        "meeting_date": meeting_date or date(2026, 1, 15),
        "summary_text": summary_text,
        "created_at": created_at or now,
        "updated_at": updated_at or now,
    }


def _extract_text(pdf_bytes):
    reader = PdfReader(BytesIO(pdf_bytes))
    return "\n".join(page.extract_text() or "" for page in reader.pages)


class ReviewerIdentityResolutionTestCase(unittest.TestCase):
    """Reviewer identity source gate (corrected, Gate B verification,
    2026-08-06). Confirms resolve_reviewer() is built from the one
    structured backend registry (config.MEMBER_DIRECTORY) — not an
    isolated per-key special case (a prior version of
    review_summary_pdf_export.py hardcoded `if member_key == "paraparan"`
    directly; that special case is gone) — never trusts a browser-supplied
    value (it isn't even passed one — only reviewer_member_key ever
    reaches this function), and the Paraparan/unknown-key fallback match
    the approved design exactly."""

    def test_member_directory_has_exactly_five_known_entries(self):
        self.assertEqual(
            set(MEMBER_DIRECTORY.keys()),
            {"mayurika", "suman", "arun", "rajiv", "paraparan"},
        )

    def test_member_directory_paraparan_role_is_auditor(self):
        self.assertEqual(MEMBER_DIRECTORY["paraparan"]["role"], "Auditor")

    def test_member_labels_unchanged_for_backward_compatibility(self):
        """MEMBER_LABELS is now derived from MEMBER_DIRECTORY (config.py)
        but every value must remain byte-for-byte identical to its
        pre-2026-08-06 literal form — every existing consumer
        (calendar_auth.py's /verify endpoint, member_schedules.py,
        member_leave.py, and their test suites) depends on these exact
        strings."""
        self.assertEqual(MEMBER_LABELS["mayurika"], "Mayurika — HR")
        self.assertEqual(MEMBER_LABELS["suman"], "Suman — Recruiting Officer")
        self.assertEqual(MEMBER_LABELS["arun"], "Arun — Implementation Officer")
        self.assertEqual(MEMBER_LABELS["rajiv"], "Rajiv — Admin Manager")

    def test_member_labels_paraparan_still_carries_no_role_suffix(self):
        """Deliberately NOT 'Paraparan — Auditor' — MEMBER_LABELS must
        never silently imply the still-open External Auditor vs.
        Accountant designation dispute has been resolved. Only
        MEMBER_DIRECTORY carries the approved 'Auditor' DISPLAY role."""
        self.assertEqual(MEMBER_LABELS["paraparan"], "Paraparan")

    def test_resolve_reviewer_reads_member_directory_not_member_labels(self):
        """Confirms resolve_reviewer()'s own module reads config.py's
        MEMBER_DIRECTORY, not MEMBER_LABELS — this would fail if
        review_summary_pdf_export.py's import were reverted to the old
        MEMBER_LABELS-splitting approach."""
        import backend.review_summary_pdf_export as pdf_export_module
        source = inspect.getsource(pdf_export_module)
        self.assertIn("MEMBER_DIRECTORY", source)

    def test_no_hardcoded_per_key_special_case_in_pdf_export_module(self):
        """Confirms the prior isolated special case
        (`if member_key == "paraparan"`) is gone from
        backend/review_summary_pdf_export.py's source — the only
        acceptable per-member-key data now lives in
        backend/config.py's MEMBER_DIRECTORY."""
        module_path = (
            Path(__file__).resolve().parents[2] / "backend" / "review_summary_pdf_export.py"
        )
        source = module_path.read_text(encoding="utf-8")
        self.assertNotIn('== "paraparan"', source)
        self.assertNotIn("_PARAPARAN_ROLE_OVERRIDE", source)

    def test_mayurika_resolves_name_and_role(self):
        entry = resolve_reviewer("mayurika")
        self.assertEqual(entry["displayName"], "Mayurika")
        self.assertEqual(entry["role"], "HR")

    def test_suman_resolves_name_and_role(self):
        entry = resolve_reviewer("suman")
        self.assertEqual(entry["displayName"], "Suman")
        self.assertEqual(entry["role"], "Recruiting Officer")

    def test_arun_resolves_name_and_role(self):
        entry = resolve_reviewer("arun")
        self.assertEqual(entry["displayName"], "Arun")
        self.assertEqual(entry["role"], "Implementation Officer")

    def test_rajiv_resolves_name_and_role(self):
        entry = resolve_reviewer("rajiv")
        self.assertEqual(entry["displayName"], "Rajiv")
        self.assertEqual(entry["role"], "Admin Manager")

    def test_paraparan_resolves_to_auditor_role(self):
        entry = resolve_reviewer("paraparan")
        self.assertEqual(entry["displayName"], "Paraparan")
        self.assertEqual(entry["role"], "Auditor")

    def test_unknown_key_resolves_safely(self):
        entry = resolve_reviewer("not-a-real-member-key")
        self.assertEqual(entry["displayName"], "Unknown")
        self.assertEqual(entry["role"], "Unknown")

    def test_none_key_resolves_safely(self):
        entry = resolve_reviewer(None)
        self.assertEqual(entry["displayName"], "Unknown")
        self.assertEqual(entry["role"], "Unknown")

    def test_frontend_registry_consistency_where_practical(self):
        """Phase 5 — 'add a consistency test against the frontend registry
        where practical.' Parses web-view/js/member-registry.js's own
        MEMBER_REGISTRY object textually (no JS runtime available from a
        Python test) and confirms every one of its 5 entries' displayName/
        role matches this backend resolver's output exactly, so the two
        registries cannot silently drift apart."""
        import re
        from pathlib import Path

        registry_path = (
            Path(__file__).resolve().parents[2]
            / "web-view" / "js" / "member-registry.js"
        )
        text = registry_path.read_text(encoding="utf-8")
        entry_re = re.compile(
            r"(\w+):\s*\{\s*displayName:\s*'([^']*)',\s*role:\s*'([^']*)'\s*\}"
        )
        frontend_entries = {key: (name, role) for key, name, role in entry_re.findall(text)}
        self.assertEqual(len(frontend_entries), 5, "expected exactly 5 frontend registry entries")
        for member_key, (display_name, role) in frontend_entries.items():
            backend_entry = resolve_reviewer(member_key)
            self.assertEqual(backend_entry["displayName"], display_name, member_key)
            self.assertEqual(backend_entry["role"], role, member_key)


class FilenameSanitizationTestCase(unittest.TestCase):
    """REQ-CAL-REV-PDF-003-FIX-02 — filename generation. Every case here is
    a fabricated employee display name, never real staff data. Format:
    Review_Summary_<Sanitized_Employee_Name>_<YYYY-MM-DD>.pdf"""

    def _sanitized(self, name):
        full = build_review_summary_pdf_filename(name, date(2026, 8, 6))
        # Strip the fixed prefix/suffix to isolate just the sanitized
        # employee-name component under test.
        return full[len("Review_Summary_"):-len("_2026-08-06.pdf")]

    def test_normal_name_is_sanitized_correctly(self):
        result = self._sanitized("Test Employee")
        self.assertEqual(result, "Test_Employee")

    def test_filename_pattern_is_exact(self):
        full = build_review_summary_pdf_filename("Mareenraj Robinsan Selvarajah", date(2026, 8, 6))
        self.assertEqual(full, "Review_Summary_Mareenraj_Robinsan_Selvarajah_2026-08-06.pdf")

    def test_spaces_become_underscores(self):
        result = self._sanitized("Test Employee Two")
        self.assertEqual(result, "Test_Employee_Two")
        self.assertNotIn(" ", result)

    def test_apostrophe_is_removed(self):
        result = self._sanitized("Test O'Brien")
        self.assertNotIn("'", result)

    def test_forward_slash_is_removed(self):
        result = self._sanitized("Test/Employee")
        self.assertNotIn("/", result)

    def test_backslash_is_removed(self):
        result = self._sanitized("Test\\Employee")
        self.assertNotIn("\\", result)

    def test_colon_and_reserved_characters_are_removed(self):
        result = self._sanitized("Test:Employee*Two?<>|")
        for ch in (":", "*", "?", "<", ">", "|"):
            self.assertNotIn(ch, result)

    def test_cr_lf_header_injection_is_blocked(self):
        result = self._sanitized("Test\r\nEmployee\t")
        self.assertNotIn("\r", result)
        self.assertNotIn("\n", result)
        self.assertNotIn("\t", result)
        full = build_review_summary_pdf_filename("Test\r\nEmployee", date(2026, 8, 6))
        self.assertNotIn("\r", full)
        self.assertNotIn("\n", full)

    def test_repeated_underscores_collapse(self):
        result = self._sanitized("Test////Employee")
        self.assertNotIn("__", result)

    def test_empty_sanitized_name_uses_employee_fallback(self):
        full = build_review_summary_pdf_filename("////\\\\::::", date(2026, 8, 6))
        self.assertEqual(full, "Review_Summary_Employee_2026-08-06.pdf")

    def test_exactly_one_pdf_extension(self):
        full = build_review_summary_pdf_filename("Test.pdf Employee.PDF", date(2026, 8, 6))
        self.assertEqual(full.lower().count(".pdf"), 1)
        self.assertTrue(full.endswith(".pdf"))

    def test_date_uses_iso_format(self):
        full = build_review_summary_pdf_filename("Test Employee", date(2026, 3, 4))
        self.assertIn("_2026-03-04.pdf", full)

    def test_non_ascii_characters_do_not_crash_and_produce_safe_ascii_filename(self):
        result = self._sanitized("Tëst Émployée")
        for ch in result:
            self.assertLess(ord(ch), 128)

    def test_path_traversal_sequence_is_neutralized(self):
        result = self._sanitized("../../etc/passwd")
        self.assertNotIn("..", result)

    def test_header_injection_sequence_is_neutralized(self):
        result = self._sanitized('Test"; filename="evil.pdf')
        self.assertNotIn('"', result)
        self.assertNotIn("\r", result)
        self.assertNotIn("\n", result)

    def test_forbidden_fields_never_appear_in_filename(self):
        # Checked against the sanitized employee-name component only — the
        # fixed "Review_Summary_" prefix legitimately contains "Summary".
        result = self._sanitized("Test Employee")
        for forbidden in ("NIC", "@", "token", "role", str(1234567890)):
            self.assertNotIn(forbidden, result)


class ContentDispositionHeaderTestCase(unittest.TestCase):
    """REQ-CAL-REV-PDF-003-FIX-02 — the combined Content-Disposition value:
    both an ASCII-safe filename= and an RFC 5987/6266 filename*=UTF-8''."""

    def test_contains_attachment(self):
        value = build_content_disposition_header("Test Employee", date(2026, 8, 6))
        self.assertTrue(value.startswith("attachment;"))

    def test_filename_form_present(self):
        value = build_content_disposition_header("Test Employee", date(2026, 8, 6))
        self.assertIn('filename="Review_Summary_Test_Employee_2026-08-06.pdf"', value)

    def test_filename_star_utf8_form_present(self):
        value = build_content_disposition_header("Test Employee", date(2026, 8, 6))
        self.assertIn("filename*=UTF-8''", value)

    def test_filename_star_preserves_non_ascii_via_percent_encoding(self):
        value = build_content_disposition_header("José García", date(2026, 8, 6))
        self.assertIn("%C3%A9", value)  # é
        self.assertIn("%C3%AD", value)  # í
        # The ASCII filename= form still exists and is transliterated.
        self.assertIn('filename="Review_Summary_Jose_Garcia_2026-08-06.pdf"', value)

    def test_cr_lf_can_never_appear_literally_in_the_header_value(self):
        value = build_content_disposition_header("Test\r\nEmployee", date(2026, 8, 6))
        self.assertNotIn("\r", value)
        self.assertNotIn("\n", value)


class PdfGenerationContentTestCase(unittest.TestCase):
    """Phase 8/12 — PDF content, using only fabricated data."""

    def test_management_aios_heading_present(self):
        pdf_bytes = build_review_summary_pdf(
            "Test Employee", "All reviewers", None, None,
            datetime(2026, 8, 6, 12, 0), [_fabricated_record()],
        )
        text = _extract_text(pdf_bytes)
        self.assertIn("Management AIOS", text)
        self.assertIn("Employee Review Summary", text)

    def test_employee_display_value_included(self):
        pdf_bytes = build_review_summary_pdf(
            "Fabricated Test Employee", "All reviewers", None, None,
            datetime(2026, 8, 6, 12, 0), [_fabricated_record()],
        )
        text = _extract_text(pdf_bytes)
        self.assertIn("Fabricated Test Employee", text)

    def test_reviewer_display_name_included(self):
        pdf_bytes = build_review_summary_pdf(
            "Test Employee", "All reviewers", None, None,
            datetime(2026, 8, 6, 12, 0), [_fabricated_record(reviewer_member_key="suman")],
        )
        text = _extract_text(pdf_bytes)
        self.assertIn("Suman", text)

    def test_reviewer_role_included(self):
        pdf_bytes = build_review_summary_pdf(
            "Test Employee", "All reviewers", None, None,
            datetime(2026, 8, 6, 12, 0), [_fabricated_record(reviewer_member_key="suman")],
        )
        text = _extract_text(pdf_bytes)
        self.assertIn("Recruiting Officer", text)

    def test_paraparan_resolves_to_auditor_in_pdf_body(self):
        pdf_bytes = build_review_summary_pdf(
            "Test Employee", "All reviewers", None, None,
            datetime(2026, 8, 6, 12, 0), [_fabricated_record(reviewer_member_key="paraparan")],
        )
        text = _extract_text(pdf_bytes)
        self.assertIn("Auditor", text)

    def test_unknown_reviewer_resolves_safely_in_pdf_body(self):
        pdf_bytes = build_review_summary_pdf(
            "Test Employee", "All reviewers", None, None,
            datetime(2026, 8, 6, 12, 0), [_fabricated_record(reviewer_member_key="not-a-real-key")],
        )
        text = _extract_text(pdf_bytes)
        self.assertIn("Unknown", text)

    def test_meeting_date_included(self):
        pdf_bytes = build_review_summary_pdf(
            "Test Employee", "All reviewers", None, None,
            datetime(2026, 8, 6, 12, 0),
            [_fabricated_record(meeting_date=date(2026, 3, 4))],
        )
        text = _extract_text(pdf_bytes)
        self.assertIn("2026-03-04", text)

    def test_complete_summary_used_not_truncated(self):
        long_text = "Fabricated filler sentence. " * 200
        pdf_bytes = build_review_summary_pdf(
            "Test Employee", "All reviewers", None, None,
            datetime(2026, 8, 6, 12, 0),
            [_fabricated_record(summary_text=long_text)],
        )
        text = _extract_text(pdf_bytes)
        # Confirm the tail of the long text (not just the start) survived —
        # a truncated export would lose this.
        self.assertIn("Fabricated filler sentence.", text)
        self.assertGreater(text.count("Fabricated filler sentence."), 100)

    def test_created_timestamp_included(self):
        pdf_bytes = build_review_summary_pdf(
            "Test Employee", "All reviewers", None, None,
            datetime(2026, 8, 6, 12, 0),
            [_fabricated_record(created_at=datetime(2026, 2, 1, 8, 15, tzinfo=timezone.utc))],
        )
        text = _extract_text(pdf_bytes)
        self.assertIn("2026-02-01", text)

    def test_updated_timestamp_included(self):
        pdf_bytes = build_review_summary_pdf(
            "Test Employee", "All reviewers", None, None,
            datetime(2026, 8, 6, 12, 0),
            [_fabricated_record(updated_at=datetime(2026, 2, 5, 10, 45, tzinfo=timezone.utc))],
        )
        text = _extract_text(pdf_bytes)
        self.assertIn("2026-02-05", text)

    def test_filter_scope_included_all_reviewers(self):
        pdf_bytes = build_review_summary_pdf(
            "Test Employee", "All reviewers", None, None,
            datetime(2026, 8, 6, 12, 0), [_fabricated_record()],
        )
        text = _extract_text(pdf_bytes)
        self.assertIn("All reviewers", text)

    def test_filter_scope_included_specific_reviewer(self):
        scope_label = reviewer_scope_label_for("mayurika")
        pdf_bytes = build_review_summary_pdf(
            "Test Employee", scope_label, None, None,
            datetime(2026, 8, 6, 12, 0), [_fabricated_record()],
        )
        text = _extract_text(pdf_bytes)
        self.assertIn("Reviewer scope", text)
        self.assertIn(scope_label, text)
        self.assertIn("—", scope_label)

    def test_reviewer_scope_label_for_combines_name_and_role(self):
        label = reviewer_scope_label_for("mayurika")
        entry = MEMBER_DIRECTORY["mayurika"]
        self.assertIn(entry["displayName"], label)
        self.assertIn(entry["role"], label)
        self.assertIn("—", label)

    def test_date_scope_included_when_supplied(self):
        pdf_bytes = build_review_summary_pdf(
            "Test Employee", "All reviewers", date(2026, 1, 1), date(2026, 1, 31),
            datetime(2026, 8, 6, 12, 0), [_fabricated_record()],
        )
        text = _extract_text(pdf_bytes)
        self.assertIn("2026-01-01", text)
        self.assertIn("2026-01-31", text)

    def test_paragraphs_and_line_breaks_accepted_by_generation(self):
        multi_paragraph = "Paragraph one.\n\nParagraph two.\nExplicit line break."
        pdf_bytes = build_review_summary_pdf(
            "Test Employee", "All reviewers", None, None,
            datetime(2026, 8, 6, 12, 0),
            [_fabricated_record(summary_text=multi_paragraph)],
        )
        # Generation must not raise on this input, and the resulting bytes
        # must be a valid, non-empty PDF.
        self.assertTrue(pdf_bytes.startswith(b"%PDF-"))
        text = _extract_text(pdf_bytes)
        self.assertIn("Paragraph one.", text)
        self.assertIn("Paragraph two.", text)

    def test_html_like_content_is_never_interpreted_as_markup(self):
        # Confirms _paragraph_text's own & < > escaping — untrusted summary
        # text can never inject markup into the generated document.
        pdf_bytes = build_review_summary_pdf(
            "Test Employee", "All reviewers", None, None,
            datetime(2026, 8, 6, 12, 0),
            [_fabricated_record(summary_text="<b>bold</b> & <script>alert(1)</script>")],
        )
        self.assertTrue(pdf_bytes.startswith(b"%PDF-"))
        text = _extract_text(pdf_bytes)
        self.assertIn("bold", text)

    def test_no_raw_ids_in_pdf_body(self):
        pdf_bytes = build_review_summary_pdf(
            "Test Employee", "All reviewers", None, None,
            datetime(2026, 8, 6, 12, 0), [_fabricated_record()],
        )
        text = _extract_text(pdf_bytes)
        # No UUID-shaped token anywhere in the extracted text.
        import re
        self.assertIsNone(
            re.search(r"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}", text)
        )

    def test_long_fabricated_content_generates_multiple_pages(self):
        long_text = "Fabricated multi-page filler sentence. " * 400
        pdf_bytes = build_review_summary_pdf(
            "Test Employee", "All reviewers", None, None,
            datetime(2026, 8, 6, 12, 0),
            [_fabricated_record(summary_text=long_text)],
        )
        reader = PdfReader(BytesIO(pdf_bytes))
        self.assertGreaterEqual(len(reader.pages), 2)

    def test_pdf_signature_valid(self):
        pdf_bytes = build_review_summary_pdf(
            "Test Employee", "All reviewers", None, None,
            datetime(2026, 8, 6, 12, 0), [_fabricated_record()],
        )
        self.assertTrue(pdf_bytes.startswith(b"%PDF-"))

    def test_pdf_metadata_title_is_generic_only(self):
        pdf_bytes = build_review_summary_pdf(
            "Fabricated Confidential Name", "All reviewers", None, None,
            datetime(2026, 8, 6, 12, 0), [_fabricated_record()],
        )
        reader = PdfReader(BytesIO(pdf_bytes))
        title = (reader.metadata or {}).get("/Title", "")
        self.assertEqual(title, "Management AIOS Employee Review Summary")
        self.assertNotIn("Fabricated Confidential Name", title)

    def test_no_disk_file_is_created_by_generation(self):
        """Phase 12 item 28 — 'no production file is created.' Patches
        builtins.open to fail loudly if the generator ever tries to open a
        file, confirming the whole pipeline (BytesIO in, bytes out) never
        touches the filesystem."""
        original_open = builtins.open

        def _forbidden_open(*args, **kwargs):
            raise AssertionError("build_review_summary_pdf must never open a file")

        builtins.open = _forbidden_open
        try:
            pdf_bytes = build_review_summary_pdf(
                "Test Employee", "All reviewers", None, None,
                datetime(2026, 8, 6, 12, 0), [_fabricated_record()],
            )
        finally:
            builtins.open = original_open
        self.assertTrue(pdf_bytes.startswith(b"%PDF-"))


class PdfLayoutRedesignTestCase(unittest.TestCase):
    """REQ-CAL-REV-PDF-003-FIX-02 — management-friendly layout: numbered
    records, confidentiality footer, page numbering, and date-scope
    phrasing. All record content below is fabricated test data."""

    def test_records_are_numbered_sequentially(self):
        pdf_bytes = build_review_summary_pdf(
            "Test Employee", "All reviewers", None, None,
            datetime(2026, 8, 6, 12, 0),
            [_fabricated_record(), _fabricated_record(), _fabricated_record()],
        )
        text = _extract_text(pdf_bytes)
        self.assertIn("Review 1", text)
        self.assertIn("Review 2", text)
        self.assertIn("Review 3", text)

    def test_confidentiality_footer_present(self):
        pdf_bytes = build_review_summary_pdf(
            "Test Employee", "All reviewers", None, None,
            datetime(2026, 8, 6, 12, 0), [_fabricated_record()],
        )
        text = _extract_text(pdf_bytes)
        self.assertIn("Confidential", text)
        self.assertIn("Management Team Use", text)

    def test_page_number_footer_present_single_page(self):
        pdf_bytes = build_review_summary_pdf(
            "Test Employee", "All reviewers", None, None,
            datetime(2026, 8, 6, 12, 0), [_fabricated_record()],
        )
        text = _extract_text(pdf_bytes)
        self.assertIn("Page 1 of 1", text)

    def test_page_number_footer_present_multi_page(self):
        long_text = "Fabricated multi-page filler sentence. " * 400
        pdf_bytes = build_review_summary_pdf(
            "Test Employee", "All reviewers", None, None,
            datetime(2026, 8, 6, 12, 0),
            [_fabricated_record(summary_text=long_text)],
        )
        reader = PdfReader(BytesIO(pdf_bytes))
        total_pages = len(reader.pages)
        self.assertGreaterEqual(total_pages, 2)
        text = _extract_text(pdf_bytes)
        self.assertIn("Page 1 of " + str(total_pages), text)
        self.assertIn("Page " + str(total_pages) + " of " + str(total_pages), text)

    def test_meeting_date_and_reviewer_line_present(self):
        pdf_bytes = build_review_summary_pdf(
            "Test Employee", "All reviewers", None, None,
            datetime(2026, 8, 6, 12, 0),
            [_fabricated_record(meeting_date=date(2026, 5, 1))],
        )
        text = _extract_text(pdf_bytes)
        self.assertIn("Meeting date: 2026-05-01", text)
        self.assertIn("Reviewed by:", text)

    def test_record_information_line_present(self):
        pdf_bytes = build_review_summary_pdf(
            "Test Employee", "All reviewers", None, None,
            datetime(2026, 8, 6, 12, 0), [_fabricated_record()],
        )
        text = _extract_text(pdf_bytes)
        self.assertIn("Record information", text)

    def test_date_scope_both_dates_supplied(self):
        pdf_bytes = build_review_summary_pdf(
            "Test Employee", "All reviewers", date(2026, 1, 1), date(2026, 1, 31),
            datetime(2026, 8, 6, 12, 0), [_fabricated_record()],
        )
        text = _extract_text(pdf_bytes)
        self.assertIn("From 2026-01-01 to 2026-01-31", text)

    def test_date_scope_from_only(self):
        pdf_bytes = build_review_summary_pdf(
            "Test Employee", "All reviewers", date(2026, 1, 1), None,
            datetime(2026, 8, 6, 12, 0), [_fabricated_record()],
        )
        text = _extract_text(pdf_bytes)
        self.assertIn("From 2026-01-01 onward", text)

    def test_date_scope_to_only(self):
        pdf_bytes = build_review_summary_pdf(
            "Test Employee", "All reviewers", None, date(2026, 1, 31),
            datetime(2026, 8, 6, 12, 0), [_fabricated_record()],
        )
        text = _extract_text(pdf_bytes)
        self.assertIn("Up to 2026-01-31", text)

    def test_date_scope_none_supplied(self):
        pdf_bytes = build_review_summary_pdf(
            "Test Employee", "All reviewers", None, None,
            datetime(2026, 8, 6, 12, 0), [_fabricated_record()],
        )
        text = _extract_text(pdf_bytes)
        self.assertIn("All available dates", text)

    def test_employee_details_section_present(self):
        pdf_bytes = build_review_summary_pdf(
            "Test Employee", "All reviewers", None, None,
            datetime(2026, 8, 6, 12, 0),
            [_fabricated_record(), _fabricated_record()],
        )
        text = _extract_text(pdf_bytes)
        self.assertIn("Reviewed employee", text)
        self.assertIn("Total review records", text)
        self.assertIn("2", text)
        self.assertIn("Generated", text)


if __name__ == "__main__":
    unittest.main()
